import React from "react";

export default function AboutPage() {
  return (
    <main className="mx-auto max-w-[922px] px-6 py-16">
      <h1 className="font-serif text-4xl md:text-5xl font-bold tracking-[0.15em] mb-8 text-left">About</h1>
      <div className="prose prose-lg font-sans text-neutral-800 leading-relaxed">
        <p>In 2017, I committed to a PhD because I was determined to become a scholar, without fully grasping what that entailed. I anticipated “hard work” but underestimated the toll it would take. Accustomed to diving into challenges, I mistook mounting psychological and physical stress signals for what they were: great big warnings that I wasn’t coping. The harder things got, the more I pressed on, no matter how lost, confused, or isolated I felt. I doubted my grasp of source material, was insecure about my research’s merit, academic jargon at conferences felt alienating, criticism struck deeply, and I overly identified with my work, all leading to persistent feelings of inadequacy. What was intended to be four years of research extended to seven (thanks Corona). Ignoring recurring anxiety attacks, I had my first burnout in 2021, followed by another in 2022. Since then, engaging with academic pursuits has been an ongoing struggle; my mental health has still not fully recovered.</p>
        <p>Throughout these challenges, I would find myself stealing time away from my research to delve into recipe books, recreate dishes that from photographs looked wholesome and picturesque, and embark on food projects as a “productive’’ way of filling and abetting hours of procrastination. Cooking offered tangible goals with immediate gratification—a stark contrast to the often intangible progress of research. Cookbooks were my adult picture books, providing nourishment for the mind without questioning my intellect. I gravitated toward recipes emphasizing small rituals, mindfulness, and presentation. Crafting something nourishing and beautiful for myself masked the insecurity and messiness I felt around my research.</p>
        <p>Over time, I’ve collected recipes and food ideas that offered these moments of respite and now wish to share them, accompanied by personal anecdotes of how they served as a balm for me. I suspect I’m not the only one who craves these simple, restorative joys. This blog aims to be a gathering place for those–like me–who find comfort and distraction in food, offering a space to share stories and recipes that provide emotional and physical sustenance. In essence, these are the 'crumbs of sanity' that help navigate life's complexities.</p>
        <h2 className="font-serif text-2xl font-bold mt-12 mb-4">A Few Remarks About This Blog:</h2>
        <ul className="list-disc pl-6">
          <li>The recipes and food ideas I post are rooted in my PhD years and what came after—the ongoing question of whether to stay in academia or try my hand at something outside of it.</li>
          <li>I am not a food writer or chef—as will become clear—but am nonetheless sharing what worked for me—practical, adaptable, and mood-dependent meals that don’t follow hard and fast rules, unless it’s obvious (a banana smoothie needs bananas, whichever way you cut it).</li>
          <li>Measurements are often rough. I believe cooking by feel is more important than precision. I also don’t know your kitchen set up, nor what ingredients are available to you so please feel free to swap, skip, or substitute where you want—as you should with any recipe. If you need help, Google (or AI) is your friend. Bee Wilson’s The Secret of Cooking also has a great guide on substitutions on pp. 216–228 (i.e., consider the flavour profile or role an ingredient serves and find something that performs similarly).</li>
          <li>Most recipes are riffs on others I’ve read but have often been adapted due to budget, laziness, seasonal availability, or personal taste (sorry, aubergine fans—you’ll see very few of them here). I create meals that work for me, so you should do the same.</li>
          <li>I live in Germany, where ingredients can be cheaper than in the UK. Good nut butters, for instance, can be as little as two euros. I chalk this up to the local crowd of yoga-loving, eco-conscious vegans who have turned nut butters into a café staple (not that I’m complaining—I’m right there with them). If such ingredients aren’t as wallet-friendly in your area or do not sate the particular virtue signalling you crave then please feel free to tweak recipes as you see fit (perhaps superfood powders or ceremonial cacao are your bag).</li>
          <li>Most recipes are designed for one, in the spirit of this blog. Multiply as needed if you're feeding others or batch cooking.</li>
          <li>I have included two types of badges: post badges and dietary badges. Post badges indicate the academic stage of the contributor (🎓), whether they are yet to enter, currently involved, or have left academia; their past, present, or future area of study (📘); and the mood behind the recipe, represented by an appropriate emoji. These badges provide a quick way for readers to find like-minded contributors and dishes that resonate with their current mental state. Dietary badges identify recipes according to dietary needs: gluten free (🥖), lactose free (🥛), vegetarian (🥕), and vegan (🌱).</li>
          <li>Cooking times are split into “hands-on” and “hands-off”. I tend to decide on what to cook depending on how long I actually can or want to be in the kitchen. A soup, for instance, may take forty-five minutes to cook but only require your engagement for fifteen minutes vs a risotto which takes a similar amount of time and needs to be babysat from start to finish.</li>
          <li>Sometimes I’ll include variations—the budget/low-energy version I first made, and a more polished version for when time or money allows.</li>
          <li>Where credit is due, I’ll name the food writers who inspired me (Nigella Lawson, you culinary goddess, I’m looking at you).</li>
        </ul>
        <p className="mt-8">Want more behind-the-scenes crumbs and daily doses of sanity? Follow us on Instagram:<br />
        <a href="https://instagram.com/crumbsofsanityblog" className="text-teal-600 underline">@crumbsofsanityblog</a></p>
      </div>
    </main>
  );
}
